import {
  Activity,
  Award,
  Bell,
  Briefcase,
  Calendar,
  ChartBar,
  ClipboardList,
  Clock,
  Compass,
  Disc3,
  FileText,
  Gavel,
  GraduationCap,
  Handshake,
  Headphones,
  House,
  Inbox,
  LayoutDashboard,
  LifeBuoy,
  ListChecks,
  Music,
  Search,
  Settings,
  Sparkles,
  Star,
  Table,
  Users,
  type LucideIcon,
} from "lucide-react";

export const shellIcons = {
  activity: Activity,
  award: Award,
  bell: Bell,
  briefcase: Briefcase,
  calendar: Calendar,
  chart: ChartBar,
  clipboard: ClipboardList,
  clock: Clock,
  compass: Compass,
  disc: Disc3,
  file: FileText,
  gavel: Gavel,
  graduation: GraduationCap,
  handshake: Handshake,
  headphones: Headphones,
  home: House,
  inbox: Inbox,
  dashboard: LayoutDashboard,
  lifebuoy: LifeBuoy,
  checklist: ListChecks,
  music: Music,
  search: Search,
  settings: Settings,
  sparkles: Sparkles,
  star: Star,
  table: Table,
  users: Users,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof shellIcons;

export function resolveIcon(icon: IconName | LucideIcon): LucideIcon {
  return typeof icon === "string" ? shellIcons[icon] : icon;
}
